// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMpZVnKci5ga0hHZZb4eXUrMxiv1lSf-g',
    appId: '1:691781568497:web:f015fc0702493af9156650',
    messagingSenderId: '691781568497',
    projectId: 'fir-project-28009',
    authDomain: 'fir-project-28009.firebaseapp.com',
    storageBucket: 'fir-project-28009.appspot.com',
    measurementId: 'G-SMQSRTCQ43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvSB8r6d9MtMWsonqXaybLfLoQyUOelv0',
    appId: '1:691781568497:android:7e974800dc063f3a156650',
    messagingSenderId: '691781568497',
    projectId: 'fir-project-28009',
    storageBucket: 'fir-project-28009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVHzOkh1-AivMpWmOKCwWqDT_hwhZ-yOo',
    appId: '1:691781568497:ios:f669431a3c7b5d05156650',
    messagingSenderId: '691781568497',
    projectId: 'fir-project-28009',
    storageBucket: 'fir-project-28009.appspot.com',
    iosBundleId: 'com.example.futurefit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVHzOkh1-AivMpWmOKCwWqDT_hwhZ-yOo',
    appId: '1:691781568497:ios:3a776d780b009650156650',
    messagingSenderId: '691781568497',
    projectId: 'fir-project-28009',
    storageBucket: 'fir-project-28009.appspot.com',
    iosBundleId: 'com.example.futurefit.RunnerTests',
  );
}
